version: "3"
services:
  spring-boot:
    build:
      context: ./mercari
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
    entrypoint: "java -jar /app/app.jar"
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: mercari
      POSTGRES_PASSWORD: mercari
      POSTGRES_USER: postgres