spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://docker_mercari_postgres_1:5432/mercari
    username: postgres
    password: mercari
server:
  servlet:
    context-path: /mercari